### ISSUE TITLE
function request

### ISSUE THREAD

**Issue by comtronix** [ritz078/emoticons-js#2]
Hi, thnx for this nice plugin.

Can you add an option for an action after hitting the button to play/listen or view a mediafile?

**Comment by ritz078** [comment]
Do you mean something like **onPlayStart** for audio and video ?

**Comment by comtronix** [comment]
(my english is not so good.)
Yes i need it also for the PDF. 
In my specific case i need to render a column on the page where your addon expands the video/pdf.

**Comment by ritz078** [comment]
Nice suggestion. I will add those features  :+1:

**Comment by comtronix** [comment]
:+1:

**Comment by ritz078** [comment]
I guess your problem is solved now. :smiley:

**Comment by comtronix** [comment]
Thank you !
