### ISSUE TITLE
Videowidth/heigt

### ISSUE THREAD

**Issue by comtronix** [ritz078/emoticons-js#3]
It would be nice if the video width can be px or % and the height can be auto-calculated.

**Comment by ritz078** [comment]
1. If you want to use % you can use css to do that. but that will just resize the video iframe (as iframes don't support dimensions in percentage.
2. And the current videoWidth and videoHeight options already are in px.
   Eg: **videoWidth** : 100 means 100px
3. Auto calculation is already implemented if you set only height then width will automatically be adjusted in appropriate ratio and vice versa.

**Comment by ritz078** [comment]
I will update the readme so that these options become more clear.

**Comment by comtronix** [comment]
Thanx for reply
