### ISSUE TITLE
Twitter feeds

### ISSUE THREAD

**Issue by comtronix** [ritz078/emoticons-js#8]
can you build in support for displaying twitter feed post?

![knipsel](https://cloud.githubusercontent.com/assets/3840400/6765356/c0196f92-cfdc-11e4-96b2-a4aa018ea9c3.PNG)

**Comment by ritz078** [comment]
Yes this can be done in the next version.

**Comment by ritz078** [comment]
Though this has been implemented its still in the unstable branch and will be merged to the master once other features planned for the next release are done.

**Comment by comtronix** [comment]
Thnx!
